# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 08:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('scopes', models.CharField(max_length=250)),
                ('auth_token', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopRedactRequest',
            fields=[
                ('shop_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('shop_origin', models.CharField(max_length=255)),
            ],
        ),
    ]
